name: flutter_cell_info
description: Lightweight  library that is build over Telephony SDK. NetMonster core is extracted from NetMonster application and backports several Telephony features to older Android devices.
version: 0.0.4
homepage: https://github.com/devsumanrazz/flutter_cell_info

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.20.0"
dependencies:
  flutter:
    sdk: flutter
  flare_flutter: ^3.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: com.sumanrajpathak.flutter_cell_info
        pluginClass: CellInfoPlugin
      ios:
        pluginClass: CellInfoPlugin
